// ============================================================
// example.js — Embedded example project (UCI Road Bike Frame)
// Used by loadExampleProject() in app.js.
// ============================================================

const CC_EXAMPLE_PROJECT = {
  "exportedAt": "2026-04-18T12:00:00.000Z",
  "version": "1.2",
  "project": {
    "id": "proj_1745000000000_bikef",
    "name": "UCI Road Bike Frame Design",
    "owner": "Kyle",
    "description": "Concept selection study for a next-generation UCI-compliant road bike frame across 18 material and construction concepts.",
    "created_at": "2026-04-18T12:00:00.000Z",
    "updated_at": "2026-04-18T12:00:00.000Z"
  },
  "goalMode": "basic",
  "goalStatement": {
    "basic": "Design and develop a UCI-compliant road bike frame that delivers competitive performance through an optimized stiffness-to-weight ratio and aerodynamic efficiency, while remaining producible at scale and serviceable across professional and consumer markets.",
    "to": "", "by": "", "using": "", "while": ""
  },
  "ilities": {
    "selected": ["reliability","safety","durability","manufacturability","maintainability","performance","sustainability","usability","affordability","testability","aesthetics"],
    "custom": []
  },
  "stakeholders": {
    "selected": ["end-user","customer","management","design-team","mfg-engineer","qa","procurement","marketing","regulatory","maintenance","supply-chain","safety-officer"],
    "custom": []
  },
  "requirements": [
    { "id": 1,  "format": "incose", "text": "The frame shall withstand a minimum of 200,000 load cycles at 1,200 N pedal load without crack initiation or propagation, per ISO 4210-6 sport cyclist fatigue testing protocol.", "type": "", "primary": "reliability", "secondaries": [], "stakeholders": ["end-user","design-team"], "scorer": "end-user" },
    { "id": 2,  "format": "incose", "text": "The frame shall pass ISO 4210-6 fork and frame fatigue testing at 100,000 cycles under 1,100 N horizontal load applied at the fork crown without structural failure or permanent set exceeding 1 mm.", "type": "", "primary": "reliability", "secondaries": [], "stakeholders": ["qa","regulatory"], "scorer": "qa" },
    { "id": 3,  "format": "incose", "text": "All tube junction fillet radii shall be no less than 2.0 mm to minimize stress concentration factors at welded, brazed, or adhesive-bonded joints.", "type": "", "primary": "reliability", "secondaries": [], "stakeholders": ["design-team","mfg-engineer"], "scorer": "design-team" },
    { "id": 4,  "format": "incose", "text": "The frame shall demonstrate a minimum safety factor of 3.0 under combined static loading at the bottom bracket shell when subjected to simultaneous rider weight (900 N) and maximum pedaling torque (250 N·m) loads.", "type": "", "primary": "reliability", "secondaries": [], "stakeholders": ["safety-officer","end-user"], "scorer": "safety-officer" },
    { "id": 5,  "format": "incose", "text": "The complete bicycle configuration shall comply with UCI Technical Regulations including a minimum bike mass of 6.8 kg, maximum tube transverse dimension of 80 mm, minimum dimension of 25 mm, and maximum aspect ratio of 3:1.", "type": "", "primary": "safety", "secondaries": [], "stakeholders": ["regulatory","qa"], "scorer": "regulatory" },
    { "id": 6,  "format": "incose", "text": "The frame shall not exhibit sudden catastrophic brittle fracture under impact loading equivalent to a 50 J drop-weight test; any structural failure mode shall be progressive and provide visible deformation or audible warning prior to complete loss of structural integrity.", "type": "", "primary": "safety", "secondaries": [], "stakeholders": ["safety-officer","end-user"], "scorer": "safety-officer" },
    { "id": 7,  "format": "incose", "text": "The frame geometry shall satisfy the UCI closed-triangle requirement (top tube, seat tube, and down tube forming a continuous closed triangle) and all geometric constraints defined in UCI Technical Regulation Article 1.3.004.", "type": "", "primary": "safety", "secondaries": [], "stakeholders": ["design-team","regulatory"], "scorer": "regulatory" },
    { "id": 8,  "format": "incose", "text": "The frame shall maintain full structural integrity and meet all original performance specifications for a minimum 5-year service life under normal use conditions of approximately 10,000 km per year for a 75 kg recreational rider.", "type": "", "primary": "durability", "secondaries": [], "stakeholders": ["end-user","customer"], "scorer": "end-user" },
    { "id": 9,  "format": "incose", "text": "Protective surface coatings (paint, anodizing, or clearcoat) shall achieve a minimum thickness of 80 µm and pass 500-hour neutral salt spray resistance testing per ISO 9227 without blistering, delamination, or corrosion breakthrough.", "type": "", "primary": "durability", "secondaries": [], "stakeholders": ["mfg-engineer","qa"], "scorer": "mfg-engineer" },
    { "id": 10, "format": "incose", "text": "All threaded interfaces (bottom bracket shell, derailleur hanger, water bottle bosses, cable stops) shall withstand 50 full torque-to-specification disassembly and reassembly cycles without measurable thread damage or pull-out strength degradation.", "type": "", "primary": "durability", "secondaries": [], "stakeholders": ["maintenance","supply-chain"], "scorer": "maintenance" },
    { "id": 11, "format": "incose", "text": "The frame shall be producible with a first-pass dimensional yield rate of ≥95% meeting all tolerance specifications in the design drawing package without requiring secondary corrective machining operations.", "type": "", "primary": "manufacturability", "secondaries": [], "stakeholders": ["mfg-engineer","procurement"], "scorer": "mfg-engineer" },
    { "id": 12, "format": "incose", "text": "All primary structural materials and frame-critical purchased components shall be sourceable from a minimum of two qualified, geographically distributed global suppliers with validated quality management systems.", "type": "", "primary": "manufacturability", "secondaries": [], "stakeholders": ["supply-chain","mfg-engineer"], "scorer": "supply-chain" },
    { "id": 13, "format": "incose", "text": "Head tube and bottom bracket shell alignment tolerances shall be held to ±0.5° angular and ±0.3 mm positional respectively, measured after all forming, welding, bonding, heat treatment, and surface finishing operations are complete.", "type": "", "primary": "manufacturability", "secondaries": [], "stakeholders": ["design-team","mfg-engineer"], "scorer": "design-team" },
    { "id": 14, "format": "incose", "text": "The frame shall be compatible with BSA 68 mm or T47 bottom bracket threading standards and accept all major road groupsets (Shimano, SRAM, Campagnolo) without requiring proprietary adapters, press-fit cups, or special tools.", "type": "", "primary": "maintainability", "secondaries": [], "stakeholders": ["maintenance","end-user"], "scorer": "maintenance" },
    { "id": 15, "format": "incose", "text": "A qualified bicycle mechanic shall be able to assess structural damage status and determine whether a frame is fit for continued service using standard visual inspection and a straight-edge gauge, without specialized equipment or manufacturer tooling.", "type": "", "primary": "maintainability", "secondaries": [], "stakeholders": ["maintenance","customer"], "scorer": "maintenance" },
    { "id": 16, "format": "incose", "text": "The internal cable and hydraulic hose routing system shall allow full replacement of a brake or shift cable by a trained mechanic within 30 minutes without frame disassembly or special insertion tools beyond standard cable cutters and a cable hook.", "type": "", "primary": "maintainability", "secondaries": [], "stakeholders": ["design-team","maintenance"], "scorer": "design-team" },
    { "id": 17, "format": "incose", "text": "Bottom bracket lateral stiffness shall be ≥120 N/mm under a 1,000 N lateral load applied at the crank arm tip at 90° from the drive side, measured as deflection at the crank tip relative to the rear dropout.", "type": "", "primary": "performance", "secondaries": [], "stakeholders": ["end-user","design-team"], "scorer": "end-user" },
    { "id": 18, "format": "incose", "text": "The frame aerodynamic drag coefficient area (CdA) shall be measurably lower than a round-tube aluminum benchmark geometry by a minimum of 10% at 0° yaw and 5° yaw angles, validated by wind tunnel or validated CFD analysis.", "type": "", "primary": "performance", "secondaries": [], "stakeholders": ["end-user","marketing"], "scorer": "end-user" },
    { "id": 19, "format": "incose", "text": "Seat tube vertical compliance shall fall within 0.5–1.5 mm of deflection under a 1,000 N vertical load applied at the seat post clamp centerline, balancing power transfer efficiency and long-ride rider comfort.", "type": "", "primary": "performance", "secondaries": [], "stakeholders": ["design-team","qa"], "scorer": "design-team" },
    { "id": 20, "format": "incose", "text": "The complete frame-and-fork system (excluding headset, stem, and seatpost) shall not exceed 1,100 g for a size 56 cm road frame, measured after all finishing operations including paint or clearcoat.", "type": "", "primary": "performance", "secondaries": [], "stakeholders": ["management","marketing"], "scorer": "management" },
    { "id": 21, "format": "incose", "text": "A minimum of 20% of frame materials by mass shall be sourced from certified recycled feedstock or responsibly-sourced suppliers with documented chain-of-custody certification (e.g., ASC, FSC, or equivalent material stewardship program).", "type": "", "primary": "sustainability", "secondaries": [], "stakeholders": ["management","supply-chain"], "scorer": "management" },
    { "id": 22, "format": "incose", "text": "Manufacturing process waste generation (tube offcuts, resin waste, abrasives, finishing consumables) shall not exceed 15% of total input material mass per completed frame unit, measured across the full production process.", "type": "", "primary": "sustainability", "secondaries": [], "stakeholders": ["procurement","supply-chain"], "scorer": "procurement" },
    { "id": 23, "format": "incose", "text": "The frame design shall be compatible with at least one recognized end-of-life material recovery program, with a documented and verifiable recycle or responsible reuse pathway for each primary structural material used in construction.", "type": "", "primary": "sustainability", "secondaries": [], "stakeholders": ["management","marketing"], "scorer": "management" },
    { "id": 24, "format": "incose", "text": "The frame shall be offered in a minimum of 6 size variants (49, 52, 54, 56, 58, and 61 cm) with stack and reach values scaled to accommodate riders across a height range of 160–195 cm based on published road bike fit data.", "type": "", "primary": "usability", "secondaries": [], "stakeholders": ["end-user","customer"], "scorer": "end-user" },
    { "id": 25, "format": "incose", "text": "The frame shall reduce high-frequency road vibration transmission by a minimum of 15% compared to a round-tube aluminum baseline, measured as RMS acceleration at the seat tube junction under standardized ISO 2631-1 road surface simulation at 30 km/h.", "type": "", "primary": "usability", "secondaries": [], "stakeholders": ["end-user","marketing"], "scorer": "end-user" },
    { "id": 26, "format": "incose", "text": "All frame-to-component contact surfaces (seat post collar, cable stops, brake mounts, water bottle bosses, derailleur hanger) shall conform to ISO and EN standard dimensions and accept commercially available components without proprietary adapters.", "type": "", "primary": "usability", "secondaries": [], "stakeholders": ["design-team","end-user"], "scorer": "design-team" },
    { "id": 27, "format": "incose", "text": "The retail price of the complete frameset (frame + fork + integrated headset) shall not exceed $3,500 USD for the base colorway at the defined target production volume of 5,000 frames per year.", "type": "", "primary": "affordability", "secondaries": [], "stakeholders": ["customer","management"], "scorer": "customer" },
    { "id": 28, "format": "incose", "text": "The bill of materials cost per frame unit at a production volume of 5,000 frames per year shall support a minimum 30% gross margin at the defined retail price, inclusive of all direct material, labor, and finishing costs.", "type": "", "primary": "affordability", "secondaries": [], "stakeholders": ["procurement","management"], "scorer": "management" },
    { "id": 29, "format": "incose", "text": "Warranty claim rate and post-sale service costs shall not exceed 3% of net revenue in Year 2 of production, supported by field data collection, failure mode tracking, and continuous improvement protocols.", "type": "", "primary": "affordability", "secondaries": [], "stakeholders": ["marketing","customer"], "scorer": "marketing" },
    { "id": 30, "format": "incose", "text": "The frame design shall include defined and documented fixture points enabling attachment of a standardized ISO 4210 fatigue test rig to the production frame without modification, drilling of additional holes, or use of custom jigs.", "type": "", "primary": "testability", "secondaries": [], "stakeholders": ["qa","regulatory"], "scorer": "qa" },
    { "id": 31, "format": "incose", "text": "All critical structural welds, bonds, or laminate joints shall be inspectable via at least one non-destructive evaluation method (dye penetrant testing, ultrasonic inspection, or digital X-ray) without frame disassembly or removal of protective coatings.", "type": "", "primary": "testability", "secondaries": [], "stakeholders": ["qa","design-team"], "scorer": "qa" },
    { "id": 32, "format": "incose", "text": "The frame surface finish program shall support a minimum of 4 distinct colorway options per model year, with inter-batch color consistency held to ΔE < 2.0 (CIELAB color space) to ensure visual uniformity across production runs.", "type": "", "primary": "aesthetics", "secondaries": [], "stakeholders": ["marketing","customer"], "scorer": "marketing" }
  ],
  "reqIdCounter": 32,
  "pairComparisons": {},
  "pugh": {
    "concepts": [
      { "id": 1,  "name": "Datum — 6061-T6 Al Round Tube",    "customFieldValues": {} },
      { "id": 2,  "name": "Aero Carbon Monocoque",             "customFieldValues": {} },
      { "id": 3,  "name": "Grade 5 Titanium TIG-Welded",       "customFieldValues": {} },
      { "id": 4,  "name": "7075-T6 Premium Aluminum",          "customFieldValues": {} },
      { "id": 5,  "name": "Hybrid Carbon-Aluminum",            "customFieldValues": {} },
      { "id": 6,  "name": "AISI 4130 Chromoly Steel",          "customFieldValues": {} },
      { "id": 7,  "name": "Mid-Modulus Carbon Endurance",      "customFieldValues": {} },
      { "id": 8,  "name": "Hydroformed 6061-T6 Aluminum",      "customFieldValues": {} },
      { "id": 9,  "name": "Carbon-Titanium Lug Hybrid",        "customFieldValues": {} },
      { "id": 10, "name": "Scandium-Aluminum Alloy",           "customFieldValues": {} },
      { "id": 11, "name": "Ultra-High Modulus Carbon",         "customFieldValues": {} },
      { "id": 12, "name": "3D-Printed Titanium Lattice",       "customFieldValues": {} },
      { "id": 13, "name": "Thermoplastic Carbon Composite",    "customFieldValues": {} },
      { "id": 14, "name": "Graphene-Enhanced Carbon",          "customFieldValues": {} },
      { "id": 15, "name": "Steel-Carbon Stay Hybrid",          "customFieldValues": {} },
      { "id": 16, "name": "Bamboo-Carbon Endurance",           "customFieldValues": {} },
      { "id": 17, "name": "Hydroformed 7075-T6 Aero",          "customFieldValues": {} },
      { "id": 18, "name": "Triaxial Braided Carbon",           "customFieldValues": {} }
    ],
    "scores": {
      "2_1":"+","2_2":"+","2_3":"+","2_4":"+","2_5":"0","2_6":"-","2_7":"0","2_8":"+","2_9":"+","2_10":"0","2_11":"-","2_12":"-","2_13":"-","2_14":"-","2_15":"-","2_16":"-","2_17":"+","2_18":"+","2_19":"+","2_20":"+","2_21":"-","2_22":"-","2_23":"-","2_24":"+","2_25":"+","2_26":"0","2_27":"-","2_28":"-","2_29":"-","2_30":"0","2_31":"-","2_32":"+",
      "3_1":"+","3_2":"+","3_3":"+","3_4":"+","3_5":"+","3_6":"+","3_7":"0","3_8":"+","3_9":"+","3_10":"+","3_11":"-","3_12":"-","3_13":"-","3_14":"+","3_15":"+","3_16":"+","3_17":"0","3_18":"0","3_19":"+","3_20":"-","3_21":"+","3_22":"0","3_23":"+","3_24":"+","3_25":"+","3_26":"+","3_27":"-","3_28":"-","3_29":"0","3_30":"+","3_31":"+","3_32":"+",
      "4_1":"+","4_2":"+","4_3":"+","4_4":"+","4_5":"0","4_6":"0","4_7":"0","4_8":"+","4_9":"+","4_10":"0","4_11":"0","4_12":"0","4_13":"-","4_14":"+","4_15":"+","4_16":"+","4_17":"+","4_18":"0","4_19":"+","4_20":"+","4_21":"0","4_22":"0","4_23":"0","4_24":"0","4_25":"0","4_26":"0","4_27":"-","4_28":"-","4_29":"0","4_30":"+","4_31":"+","4_32":"0",
      "5_1":"+","5_2":"+","5_3":"0","5_4":"+","5_5":"0","5_6":"0","5_7":"0","5_8":"0","5_9":"0","5_10":"-","5_11":"-","5_12":"-","5_13":"-","5_14":"-","5_15":"-","5_16":"-","5_17":"+","5_18":"+","5_19":"+","5_20":"+","5_21":"-","5_22":"-","5_23":"-","5_24":"+","5_25":"+","5_26":"0","5_27":"-","5_28":"-","5_29":"-","5_30":"0","5_31":"0","5_32":"+",
      "6_1":"+","6_2":"+","6_3":"+","6_4":"+","6_5":"0","6_6":"+","6_7":"0","6_8":"0","6_9":"-","6_10":"+","6_11":"+","6_12":"+","6_13":"+","6_14":"+","6_15":"+","6_16":"+","6_17":"-","6_18":"-","6_19":"-","6_20":"-","6_21":"+","6_22":"+","6_23":"+","6_24":"+","6_25":"+","6_26":"+","6_27":"+","6_28":"+","6_29":"+","6_30":"+","6_31":"+","6_32":"0",
      "7_1":"+","7_2":"+","7_3":"+","7_4":"+","7_5":"0","7_6":"0","7_7":"0","7_8":"+","7_9":"+","7_10":"0","7_11":"-","7_12":"-","7_13":"-","7_14":"-","7_15":"-","7_16":"-","7_17":"+","7_18":"+","7_19":"+","7_20":"+","7_21":"-","7_22":"-","7_23":"-","7_24":"+","7_25":"+","7_26":"0","7_27":"-","7_28":"-","7_29":"0","7_30":"0","7_31":"-","7_32":"+",
      "8_1":"0","8_2":"0","8_3":"+","8_4":"0","8_5":"0","8_6":"0","8_7":"0","8_8":"0","8_9":"0","8_10":"0","8_11":"+","8_12":"+","8_13":"+","8_14":"+","8_15":"+","8_16":"0","8_17":"+","8_18":"+","8_19":"0","8_20":"+","8_21":"+","8_22":"+","8_23":"0","8_24":"+","8_25":"+","8_26":"0","8_27":"0","8_28":"0","8_29":"+","8_30":"+","8_31":"+","8_32":"+",
      "9_1":"+","9_2":"+","9_3":"+","9_4":"+","9_5":"+","9_6":"+","9_7":"+","9_8":"+","9_9":"+","9_10":"+","9_11":"-","9_12":"-","9_13":"-","9_14":"+","9_15":"+","9_16":"0","9_17":"+","9_18":"+","9_19":"+","9_20":"+","9_21":"0","9_22":"-","9_23":"0","9_24":"+","9_25":"+","9_26":"+","9_27":"-","9_28":"-","9_29":"-","9_30":"0","9_31":"0","9_32":"+",
      "10_1":"+","10_2":"+","10_3":"+","10_4":"+","10_5":"+","10_6":"+","10_7":"0","10_8":"+","10_9":"+","10_10":"+","10_11":"+","10_12":"-","10_13":"0","10_14":"+","10_15":"+","10_16":"+","10_17":"+","10_18":"+","10_19":"+","10_20":"+","10_21":"-","10_22":"0","10_23":"-","10_24":"0","10_25":"0","10_26":"0","10_27":"-","10_28":"-","10_29":"-","10_30":"+","10_31":"+","10_32":"0",
      "11_1":"-","11_2":"-","11_3":"-","11_4":"-","11_5":"-","11_6":"-","11_7":"0","11_8":"0","11_9":"+","11_10":"0","11_11":"-","11_12":"-","11_13":"-","11_14":"-","11_15":"-","11_16":"-","11_17":"+","11_18":"+","11_19":"-","11_20":"+","11_21":"-","11_22":"-","11_23":"-","11_24":"-","11_25":"-","11_26":"0","11_27":"-","11_28":"-","11_29":"-","11_30":"-","11_31":"-","11_32":"+",
      "12_1":"0","12_2":"0","12_3":"+","12_4":"+","12_5":"+","12_6":"+","12_7":"0","12_8":"+","12_9":"+","12_10":"+","12_11":"-","12_12":"-","12_13":"-","12_14":"+","12_15":"+","12_16":"0","12_17":"+","12_18":"+","12_19":"+","12_20":"+","12_21":"0","12_22":"-","12_23":"+","12_24":"+","12_25":"+","12_26":"+","12_27":"-","12_28":"-","12_29":"-","12_30":"0","12_31":"0","12_32":"+",
      "13_1":"0","13_2":"0","13_3":"0","13_4":"+","13_5":"0","13_6":"+","13_7":"0","13_8":"+","13_9":"+","13_10":"+","13_11":"+","13_12":"0","13_13":"0","13_14":"+","13_15":"+","13_16":"+","13_17":"0","13_18":"0","13_19":"+","13_20":"0","13_21":"+","13_22":"+","13_23":"+","13_24":"0","13_25":"0","13_26":"0","13_27":"-","13_28":"-","13_29":"0","13_30":"+","13_31":"+","13_32":"0",
      "14_1":"+","14_2":"+","14_3":"+","14_4":"+","14_5":"0","14_6":"0","14_7":"0","14_8":"+","14_9":"+","14_10":"+","14_11":"-","14_12":"-","14_13":"-","14_14":"-","14_15":"-","14_16":"-","14_17":"+","14_18":"+","14_19":"+","14_20":"+","14_21":"-","14_22":"-","14_23":"-","14_24":"+","14_25":"+","14_26":"+","14_27":"-","14_28":"-","14_29":"-","14_30":"0","14_31":"-","14_32":"+",
      "15_1":"+","15_2":"+","15_3":"+","15_4":"+","15_5":"+","15_6":"+","15_7":"0","15_8":"0","15_9":"-","15_10":"+","15_11":"-","15_12":"-","15_13":"-","15_14":"+","15_15":"+","15_16":"+","15_17":"-","15_18":"-","15_19":"0","15_20":"-","15_21":"+","15_22":"0","15_23":"+","15_24":"+","15_25":"+","15_26":"+","15_27":"0","15_28":"0","15_29":"0","15_30":"0","15_31":"0","15_32":"+",
      "16_1":"0","16_2":"-","16_3":"0","16_4":"0","16_5":"0","16_6":"0","16_7":"0","16_8":"-","16_9":"-","16_10":"-","16_11":"-","16_12":"-","16_13":"-","16_14":"-","16_15":"-","16_16":"-","16_17":"-","16_18":"-","16_19":"-","16_20":"-","16_21":"+","16_22":"+","16_23":"+","16_24":"+","16_25":"+","16_26":"0","16_27":"-","16_28":"-","16_29":"-","16_30":"-","16_31":"-","16_32":"+",
      "17_1":"+","17_2":"+","17_3":"+","17_4":"+","17_5":"0","17_6":"0","17_7":"0","17_8":"+","17_9":"+","17_10":"0","17_11":"+","17_12":"+","17_13":"+","17_14":"0","17_15":"+","17_16":"0","17_17":"+","17_18":"+","17_19":"+","17_20":"+","17_21":"+","17_22":"+","17_23":"0","17_24":"+","17_25":"+","17_26":"+","17_27":"-","17_28":"-","17_29":"0","17_30":"+","17_31":"+","17_32":"+",
      "18_1":"+","18_2":"+","18_3":"+","18_4":"+","18_5":"0","18_6":"0","18_7":"0","18_8":"+","18_9":"+","18_10":"+","18_11":"+","18_12":"-","18_13":"+","18_14":"-","18_15":"-","18_16":"-","18_17":"+","18_18":"+","18_19":"+","18_20":"+","18_21":"-","18_22":"-","18_23":"-","18_24":"0","18_25":"0","18_26":"0","18_27":"0","18_28":"0","18_29":"0","18_30":"+","18_31":"+","18_32":"+"
    },
    "advBackup": {},
    "settings": { "advancedScoring": false, "showMTHUS": true, "showMAS": true },
    "counter": 18,
    "datumPerformance": {
      "1":  { "mas": "0" },
      "5":  { "mas": "0" },
      "6":  { "mas": "0" },
      "7":  { "mas": "0" },
      "20": { "mas": "0" }
    },
    "conceptPerformance": {}
  },
  "convergence": {
    "selectedConceptId": "7",
    "rationale": "The Mid-Modulus Carbon Endurance frame (Concept 7) earned the highest net positive score across all 32 requirements and all 11 lifecycle properties. It outperformed the Datum in every performance category — meeting the UCI stiffness-to-weight targets, vibration damping threshold, and aerodynamic drag coefficient — while avoiding the affordability and manufacturability penalties incurred by higher-modulus and exotic-hybrid options. Unlike Concept 2 (Aero Carbon Monocoque), which scored strongly on performance but carried repeated negatives on repairability, sustainability, and retail price, Concept 7 maintained positive or neutral scores across the full requirement set. Grade 5 Titanium (Concept 3) scored well on durability and rideability but could not meet the $3,500 frameset retail ceiling at the target production volume of 5,000 units per year. The Mid-Modulus Carbon layup is a proven, supplier-mature process with documented tooling paths at our contract manufacturing partner, significantly reducing schedule and qualification risk relative to the braided carbon and thermoplastic composite alternatives. All 12 stakeholder groups rated the selected concept favorably against their primary requirements. The design team confirmed compatibility with standard ISO component interfaces and a clean path to the 6-size variant requirement without unique tooling per size.",
    "lessons": {
      "req": "The $3,500 retail price ceiling (REQ-27) and 30% gross margin floor (REQ-28) were the most discriminating requirements in the matrix — they eliminated five otherwise high-performing concepts including Grade 5 Titanium, 3D-Printed Titanium Lattice, Graphene-Enhanced Carbon, Carbon-Titanium Lug Hybrid, and Ultra-High Modulus Carbon. Future concept generation sessions should front-load cost feasibility screening before investing time scoring exotic material options. The fatigue test fixture interface requirement (REQ-30) was underspecified at the start; clarifying it earlier would have eliminated two additional concepts in the first round.",
      "concepts": "Seventeen alternatives were evaluated against the Datum. The most surprising finding was how poorly the Aero Carbon Monocoque (Concept 2) scored on the full requirement set despite its strong brand appeal — the manufacturing complexity and repairability deficiencies accounted for five negative scores that no other high-performance concept suffered. The Triaxial Braided Carbon (Concept 18) was the strongest alternative to the selected concept but was eliminated on supply chain readiness and tooling lead time, not on technical merit — this concept should be reconsidered if manufacturing capability matures within the next 18 months. The Bamboo-Carbon Endurance concept (Concept 16) generated significant internal debate and validated the need for explicit sustainability scoring; it performed better than expected on lifecycle properties but could not meet stiffness targets.",
      "assumption": "The most consequential assumption was that carbon fiber prepreg pricing would remain within 8% of current spot rates at the target production volume. This drove affordability scores for all 10 carbon-based concepts. A 15%+ price spike would materially change the matrix outcome and elevate the 7075-T6 Premium Aluminum concept. The second critical assumption was UCI regulatory stability — the current weight floor (6.8 kg) and no-monocoque-restriction rules were treated as fixed; any rule changes affecting integrated frame-fork-bar systems would require a full matrix re-run. Supply chain readiness for mid-modulus T700/T800 prepreg at 5,000 frames/year was assumed accessible through two qualified suppliers; single-source dependency would add risk that was not scored in this matrix.",
      "different": "We would generate a broader initial concept set focused on manufacturing process variants within the carbon fiber family, rather than material variants across entirely different material classes. Carbon variants (different modulus grades, layup orientations, cure methods) represent the realistic decision space at this stage, and populating 12 of 17 non-datum concepts with non-carbon options diluted scoring time without changing the outcome. We would also establish firm cost-feasibility thresholds before the first Pugh pass, reducing the matrix from 18 to approximately 10 concepts for the scored run. Finally, we would engage the regulatory stakeholder earlier — the UCI compliance requirements drove 6 of the 32 requirements and their interpretations shaped scoring for every performance concept."
    },
    "risks": "1. Carbon prepreg material cost volatility — 15%+ price increase would erode margin floor (REQ-28) and may require concept re-evaluation toward Hydroformed 7075-T6 Aero (Concept 17). Mitigation: negotiate 12-month forward pricing with two qualified suppliers before tooling commitment.\n\n2. Contract manufacturer tooling lead time — mid-modulus carbon monocoque tooling is estimated at 14–18 weeks. Any slip pushes first article inspection past the Q3 target. Mitigation: issue tooling RFQ within 30 days of this convergence sign-off.\n\n3. UCI rule stability — integrated cockpit and dropped-bar aerodynamic appendage rules are under active review. If the UCI bans certain aerodynamic tube profiles before homologation, the frame geometry may require revision. Mitigation: monitor UCI Technical Regulations Bulletin quarterly; assign regulatory stakeholder as standing monitor.\n\n4. 6-size variant tooling cost — offering 6 frame sizes (REQ-24) requires 6 unique mold sets for a monocoque lay-up. Unit economics at 5,000 frames/year may not support equal run quantities across all sizes. Mitigation: analyze sales distribution data from comparable product lines; plan production allocation before tool order.\n\n5. Repairability field expectation — end-user and maintenance stakeholder groups flagged that carbon monocoque frames are perceived as non-repairable in the field. This is a brand communication and warranty design risk, not a technical one. Mitigation: define warranty replacement program and publish repair-or-replace policy before product launch.",
    "nextSteps": [
      { "id": "ns1", "what": "Issue tooling RFQ to two qualified contract carbon manufacturers for mid-modulus monocoque tooling across all 6 frame sizes", "who": "Design Team / Procurement", "when": "2026-05-02" },
      { "id": "ns2", "what": "Negotiate 12-month forward pricing agreement for T700/T800 prepreg with primary and secondary suppliers", "who": "Procurement", "when": "2026-05-16" },
      { "id": "ns3", "what": "Complete detailed FEA on final tube profile geometry to confirm stiffness-to-weight ratio meets REQ-1 and REQ-2 before tooling release", "who": "Design Team", "when": "2026-05-09" },
      { "id": "ns4", "what": "Draft warranty replacement program and repair-or-replace policy document for Marketing and Customer review", "who": "Marketing / Management", "when": "2026-05-23" },
      { "id": "ns5", "what": "Assign regulatory stakeholder as standing UCI Technical Regulations monitor; set quarterly review cadence", "who": "Regulatory", "when": "2026-04-25" },
      { "id": "ns6", "what": "Analyze comparable product sales distribution data to determine frame size production allocation across 6 variants", "who": "Management / Marketing", "when": "2026-05-09" },
      { "id": "ns7", "what": "Schedule first article inspection milestone with contract manufacturer; confirm Q3 target date feasibility", "who": "Design Team / QA", "when": "2026-05-30" }
    ],
    "closedAt": "2026-04-18T17:30:00.000Z"
  }
};
